### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Besjan** [vincent290587/ant_desktop#2]
Hi, is it possible to get the speed in Unreal using Kickr Snap?
Thank in advance.

**Comment by vincent290587** [comment]
Currently only page 25 is supported, the speed is in page 16 (ANT+ fitness equipment specification).
The corresponding code is in the file https://github.com/vincent290587/ant_desktop/blob/master/AntPlusPlugin/Source/AntPlusPlugin/Private/AntPlusPluginBPLibrary.cpp

Should be easy to implement
